total = int(input())
cubes = list(map(int, input().split()))
result = str(sorted(cubes))
result = result.replace('[', '' )
result = result.replace(']', '' )
result = result.replace(',', '')
print(result)